### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Lujaw** [gillstrom/battery-level#1]
when using the cli on  lenovo laptop, it gives the following error

Cannot read property 'length' of undefined
on this file
battery-level/index.js:24
                res = res.percentage.slice(0, res.percentage.length);

**Comment by kevva** [comment]
@Lujaw, what OS are you on? If you log `res`, do you get any output?

**Comment by gillstrom** [comment]
@Lujaw could you try again after `1.3.0`?

**Comment by kevva** [comment]
Going to close this due to inactivity.
