### ISSUE TITLE
Add charging indication

### ISSUE THREAD

**Issue by EladBezalel** [gillstrom/battery-level#4]
This could be awesome feature :)

**Comment by EladBezalel** [comment]
In windows:
`WMIC Path Win32_Battery Get BatteryStatus`
returns 1 if discharging and 2 if charging

**Comment by gillstrom** [comment]
https://github.com/gillstrom/is-charging might be what you're looking for right?

Sorry for letting you wait.

**Comment by EladBezalel** [comment]
Don't you think it should be provided in battery-level as well?
When i ask for the battery level i would probably want to know if it's charging or not

**Comment by kevva** [comment]
Maybe in the CLI, but probably not using the API.
